name: Task build, test, style

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v2
      - name: Setup Node ⚙️
        uses: actions/setup-node@v2
        with:
          node-version: "16.x"
      - name: Install 🚦
        run: yarn
      - name: Build 🔨
        run: yarn build

  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v2
      - name: Setup Node ⚙️
        uses: actions/setup-node@v2
        with:
          node-version: "16.x"
      - name: Install 🚦
        run: yarn
      - name: Test 🧪
        run: yarn test

  style:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v2
      - name: Setup Node ⚙️
        uses: actions/setup-node@v2
        with:
          node-version: "16.x"
      - name: Install 🚦
        run: yarn
      - name: Style 💅
        run: yarn style
